name: auth_domain
description: A dart package that includes auth domain elements.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  # Immutable elements
  freezed_annotation: ^1.1.0

dev_dependencies:
  # Code generation
  build_runner: ^2.1.7

  # Immutable elements
  freezed: ^1.1.1

  # Linting
  lint_rules:
    path: ../../../lint_rules

  # Testing
  test: ^1.20.1
