name: flutter_my_starred_repos

# Check for packages within the current folder and all sub-folders.
packages:
  - "**"

# Workaround to ignore l10n gen packages.
ignore:
  - synthetic_package

scripts:
  g:
    description: Run code generation for a selected package.
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
  G:
    description: Run code generation for all packages.
    run: melos run g --no-select

  f:
    description: Format codebase for a selected package.
    run: melos exec -c 1 -- flutter format lib test
    select-package:
  F:
    description: Format codebase for all packages.
    run: melos run f --no-select
  F:ci:
    description: Format codebase for all packages and stop if a change is identified.
    run: melos exec --fail-fast -- flutter format --set-exit-if-changed lib test

  a:
    description: Analyze codebase for a selected package and consider infos and warnings as errors.
    run: melos exec -c 1 -- flutter analyze --fatal-infos --fatal-warnings
    select-package:
  A:
    description: Analyze codebase for all packages and consider infos and warnings as errors.
    run: melos run a --no-select
  A:ci:
    description: Analyze codebase for all packages considering infos and warnings as errors.
    run: melos exec --fail-fast -- flutter analyze --no-pub --fatal-infos --fatal-warnings

  t:
    description: Run tests for a selected package in random order.
    run: melos exec -c 1 -- flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random
    select-package:
      dir-exists: test
  T:
    description: Run tests for all packages in random order.
    run: melos run t --no-select
  T:ci:
    description: Run tests for all packages in random order.
    run: melos exec --fail-fast --dir-exists=test -- flutter test -x ci-only --no-pub --coverage -r expanded --test-randomize-ordering-seed random

  M:
    description: Merge all packages coverage data ignoring data related to generated files.
    run: >
      dart run cli/bin/rm.dart coverage/merged.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- dart run MELOS_ROOT_PATH/cli/bin/cov.dart merge --origin ./coverage/lcov.info --destination MELOS_ROOT_PATH/coverage/merged.lcov.info --ignore-patterns \.g\.dart,\.freezed\.dart
