name: flutter_my_starred_repos

# Check for packages within the current folder and all sub-folders.
packages:
  - "**"

# Workaround to ignore l10n gen packages and Windows-specific packages.
ignore:
  - ".dart_tool/**"
  - "windows/flutter/ephemeral/**"

scripts:
  c:
    description: Drop the `build/` and `.dart_tool/` folders from a selected package.
    run: melos exec -c 1 -- flutter clean
    select-package:
  C:
    description: Drop the `build/` and `.dart_tool/` folders from all packages.
    run: melos run c --no-select

  d:
    description: Install dependencies for a selected package.
    run: melos exec -c 1 -- flutter pub get
    select-package:
  D:
    description: Install dependencies for all packages.
    run: melos run d --no-select
  D:ci:
    description: Install dependencies for all packages.
    run: melos exec -- flutter pub get

  g:
    description: Run code generation for a selected package.
    run: melos exec -c 1 -- flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
  G:
    description: Run code generation for all packages.
    run: melos run g --no-select

  f:
    description: Format codebase for a selected package.
    run: melos exec -c 1 -- flutter format lib test
    select-package:
  F:
    description: Format codebase for all packages.
    run: melos run f --no-select
  F:ci:
    description: Format codebase for all packages and stop if a change is identified.
    run: melos exec --fail-fast -- flutter format --set-exit-if-changed lib test

  a:
    description: Analyze codebase for a selected package and consider warnings as errors.
    run: melos exec -c 1 -- flutter analyze --no-fatal-infos --fatal-warnings
    select-package:
  A:
    description: Analyze codebase for all packages and consider warnings as errors.
    run: melos run a --no-select
  A:ci:
    description: Analyze codebase for all packages considering infos and warnings as errors.
    run: melos exec --fail-fast -- flutter analyze --no-pub --fatal-infos --fatal-warnings

  t:
    description: Run tests for a selected package in random order.
    run: melos exec -c 1 -- flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random
    select-package:
      dir-exists: test
  T:
    description: Run tests for all packages in random order.
    run: melos run t --no-select
  T:ci:
    description: Run tests for all packages in random order.
    run: melos exec --fail-fast --dir-exists=test -- flutter test -x ci-only --no-pub --coverage -r expanded --test-randomize-ordering-seed random

  M:
    description: Merge all packages coverage data ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/merged.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/merged.lcov.info --filters \.g\.dart,\.freezed\.dart

  WF:
    description: Run full local workflow
    run: melos run D && melos run F && melos run A && melos run T && melos run M
  WF:ci:
    description: Run full CI workflow
    run: melos run D:ci && melos run F:ci && melos run A:ci && melos run T:ci && melos run M
