name: flutter_my_starred_repos
description: A Flutter app to manage personal GitHub starred repositories.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

  # TODO: Remove package.
  # Authentication
  oauth2: ^2.0.0

  # Functional programming
  dartz: ^0.10.1
  oxidized: ^5.1.0

  # GraphQL client
  graphql: ^5.0.0

  # HTTP client
  dio: ^4.0.4

  # Immutable elements
  freezed_annotation: ^1.1.0
  kt_dart: ^0.10.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Local storage
  sembast: ^3.1.1+1

  # Logging
  emoji_lumberdash: ^2.0.0
  lumberdash: ^3.0.0

  # Routing/Navigation
  auto_route: ^3.2.1

  # State management
  flutter_bloc: ^7.3.3

  # UI
  cached_network_image: ^3.2.0
  material_design_icons_flutter: ^5.0.6595
  webview_flutter: ^3.0.0

  # Utils
  checked_yaml: ^2.0.1
  path: ^1.8.0
  path_provider: ^2.0.8

  # Auth features
  auth:
    path: features/auth
  starred_repos:
    path: features/starred_repos

  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.1.7

  # Immutable elements
  freezed: ^1.1.1

  # Linting
  lint_rules:
    path: lint_rules

  # Routing/Navigation
  auto_route_generator: ^3.2.1

  # Serialization
  json_serializable: ^6.1.3

  # Testing
  bloc_test: ^8.5.0
  build_verify: ^3.0.0
  mocktail: ^0.2.0
  test: ^1.20.1

dependency_overrides:
  meta: ^1.7.0
  test_api: ^0.4.2

flutter:
  uses-material-design: true

  # Flutter generation
  generate: true

  assets:
    - assets/app_icon/
    - assets/config/
