name: auth_rds
description: An auth remote data source.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Auth
  oauth2: ^2.0.0

  # Immutable elements
  freezed_annotation: ^0.14.2

  # Packages
  auth_config:
    path: ../auth_config
  auth_domain:
    path: ../auth_domain

dev_dependencies:
  # Code generation
  build_runner: any

  # Immutable elements
  freezed: any

  # Linting
  lint_rules:
    path: ../../lint_rules

  # Testing
  mocktail: any
  test: any
