name: auth_service
description: An auth service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Other packages
  dartz: ^0.10.1

  # Auth feature
  auth:
    path: ../../../auth

  # Data sources
  auth_rds:
    path: ../../data_sources/auth_rds

dev_dependencies:
  # Linting
  lint_rules:
    path: ../../../../lint_rules

  # Testing
  mocktail: ^0.2.0
  test: ^1.20.1

dependency_overrides:
  meta: ^1.7.0
