name: auth_rds
description: An auth remote data source.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Auth
  oauth2: ^2.0.0

  # Immutable elements
  freezed_annotation: ^1.1.0

  # Packages
  auth_config:
    path: ../../auth_config
  auth_domain:
    path: ../../auth_domain

dev_dependencies:
  # Code generation
  build_runner: ^2.1.7

  # Immutable elements
  freezed: ^1.1.1

  # Linting
  lint_rules:
    path: ../../../../lint_rules

  # Testing
  mocktail: ^0.2.0
  test: ^1.20.1

dependency_overrides:
  meta: ^1.7.0
