name: Testing

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "test/**"
      - "web/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"
  push:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "web/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"

jobs:
  min-conditions:
    name: Format, analyze and ensure up-to-date code generation (minimal conditions)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Setup Java actions
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter actions
        uses: subosito/flutter-action@v1

      - name: Install tools
        run: flutter pub global activate melos

      - name: Initialize tools
        run: melos bs

      - name: Install dependencies
        run: melos exec -- flutter pub get

      - name: Format Dart files within `lib` and `test` folders and abort on formatting changes
        run: melos run F:ci

      - name: Analyze Dart files considering infos and warnings as failures
        run: melos run A:ci

      # TODO: Enable including code gen data caching.
      # - name: Ensure up-to-date code generation
      #   run: melos exec --depends-on=test --file-exists=test/up_to_date_code_gen_test.dart -- flutter pub run test --run-skipped -t ci-only test/up_to_date_code_gen_test.dart

  test:
    needs: min-conditions
    name: Test app implementation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Setup Java actions
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter actions
        uses: subosito/flutter-action@v1

      - name: Install tools
        run: flutter pub global activate melos

      - name: Initialize tools
        run: melos bs

      - name: Install dependencies
        run: melos exec -- flutter pub get

      - name: Run tests adn generate coverage
        run: melos run T:ci

      - name: Unify coverage data
        run: melos run M

      - name: Check 100% code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "**/*.freezed.dart **/*.g.dart **/*.gr.dart"
